//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExpertsClientPage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }
    
        public int PackageId { get; set; }
        public string PkgName { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> PkgStartDate { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> PkgEndDate { get; set; }
        public string PkgDesc { get; set; }

        [DisplayFormat(DataFormatString = "{0:c}")]
        public decimal PkgBasePrice { get; set; }
        public Nullable<decimal> PkgAgencyCommission { get; set; }
        public string PkgImageFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
